// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTndQ1ZiV3RTg0g0jBsg0dQpBShFsyK-8',
    appId: '1:924861521725:web:61f0b4a7c581f9fd55af54',
    messagingSenderId: '924861521725',
    projectId: 'practica-1-86462',
    authDomain: 'practica-1-86462.firebaseapp.com',
    storageBucket: 'practica-1-86462.appspot.com',
    measurementId: 'G-RX3ZWQQ87P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmKPqjFI1qtS2a5f_DsbriWhznPiB_9Ic',
    appId: '1:924861521725:android:9e20068a2ebd04eb55af54',
    messagingSenderId: '924861521725',
    projectId: 'practica-1-86462',
    storageBucket: 'practica-1-86462.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw-Y9Slqcyl4ILruvJUfu-chxBRprJJoc',
    appId: '1:924861521725:ios:f04be8c9d3dc83ae55af54',
    messagingSenderId: '924861521725',
    projectId: 'practica-1-86462',
    storageBucket: 'practica-1-86462.appspot.com',
    iosClientId:
        '924861521725-lbn87h8m9hecl6nunllbvpub9ovnqfcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.practica1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw-Y9Slqcyl4ILruvJUfu-chxBRprJJoc',
    appId: '1:924861521725:ios:f04be8c9d3dc83ae55af54',
    messagingSenderId: '924861521725',
    projectId: 'practica-1-86462',
    storageBucket: 'practica-1-86462.appspot.com',
    iosClientId:
        '924861521725-lbn87h8m9hecl6nunllbvpub9ovnqfcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.practica1',
  );
}
